# Global
methink_html_homepage:
    pattern:  /
    defaults: { _controller: MethinkHtmlBundle:Default:index }

# methink_html_login:
#     pattern: /login/
#     defaults: { _controller: MethinkHtmlBundle:Account:login }

# methink_html_login_check:
#     pattern: /login_check

# methink_html_logout:
#     pattern: /logout

# Event
methink_html_event_index:
    pattern: /event/
    defaults: { _controller: MethinkHtmlBundle:Event:index }

methink_html_event_create:
    pattern: /event/create
    defaults: { _controller: MethinkHtmlBundle:Event:create }

methink_html_event_edit:
    pattern: /event/edit/{event_id}
    defaults: { _controller: MethinkHtmlBundle:Event:edit }

methink_html_event_delete:
    pattern: /event/delete/{event_id}
    defaults: { _controller: MethinkHtmlBundle:Event:delete }