methink_html_homepage:
    pattern:  /
    defaults: { _controller: MethinkHtmlBundle:Default:index }

methink_html_event_index:
    pattern: /event/
    defaults: { _controller: MethinkHtmlBundle:Event:index }

methink_html_event_create:
    pattern: /event/create
    defaults: { _controller: MethinkHtmlBundle:Event:create }
    # methods: [GET]

# methink_html_event_create_process:
#     pattern: /event/create
#     defaults: { _controller: MethinkHtmlBundle:Event:createProcess }
#     methods: [POST]